services:
  parakeet:
    build: .
    container_name: parakeet-stt
    ports:
      - "8888:8000"
    # env_file: .env               # TODO
    environment:
      LOG_LEVEL: "INFO"
    volumes:
      - ./data/cache:/root/.cache
      - ./parakeet_service:/app/parakeet_service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    #     limits:
    #       cpus: "4"
    #       memory: 4G
    restart: unless-stopped
